#!/usr/bin/env php
<?php
/**
 * This is an example PHP script that uses Rest API to pull forex quotes for EUR/USD.
 *
 * Replace the API_KEY to your own api key and run ./forex in your terminal.
 * If you are getting permission issue, run "chmod +x ./forex"
 */

require __DIR__ . '/../../vendor/autoload.php';

$client = (new ErsinDemirtas\PolygonIO\Client('API_KEY'))->rest();
$forex = $client->forex();

$rate = $forex->realTimeCurrencyConversion('EUR', 'USD');
