#!/usr/bin/env php
<?php

require __DIR__ . '/../../vendor/autoload.php';

$client = new PolygonIO\PolygonIO('API_KEY');

$currencies = ['C.USD'];

$client->websockets->forex->connect($currencies, function($data) {
    var_dump($data);
});
