#!/usr/bin/env php
<?php
/**
 * This is an example PHP script that uses websocket to subscribe forex topic
 * and receive quotes for C.USD.
 *
 * Replace the API_KEY to your own api key and run ./forex in your terminal.
 * If you are getting permission issue, run "chmod +x ./forex"
 */

require __DIR__ . '/../../vendor/autoload.php';

$client = new ErsinDemirtas\PolygonIO\Client('API_KEY');

$currencies = ['C.USD'];

$client->websockets->forex->connect($currencies, function($data) {
    var_dump($data);
});
